language: java

matrix:
  include:
    - jdk: oraclejdk7
      env: CONTAINER=3.x
    - jdk: oraclejdk8
      env: CONTAINER=4.x
    - jdk: oraclejdk8
      env: CONTAINER=payara-4

cache:
  directories:
    - $HOME/.m2

script:
- ./mvnw clean verify -P$CONTAINER
