language: java

matrix:
  include:
    - jdk: openjdk7
      env: CONTAINER=3.x
    - jdk: oraclejdk8
      env: CONTAINER=4.x
    - jdk: oraclejdk8
      env: CONTAINER=5.x
    - jdk: oraclejdk8
      env: CONTAINER=payara-4

cache:
  directories:
    - $HOME/.m2

before_install:
  - sed -i.bak -e 's|http://repo.maven.apache.org/maven2|https://repo.maven.apache.org/maven2|g' $HOME/.m2/settings.xml

install: true

script:
- ./mvnw clean install -P$CONTAINER
